sudo: required
language: python

services:
- docker

before_install:
- sudo apt-get update
- sudo apt-get install docker-engine
- sudo service docker restart
- make build

script:
- make test
- make push

after_success:
- pip install fabric
- fab deploy
