name: auth-proxy
resolver:
  host: 10.0.0.10
  ttl: 1s
services:
  album-manager:
    server: svc.cluster.local service=_https._tcp.album-manager.default
    expose_external: true
    healthcheck: true
  pages:
    server: svc.cluster.local service=_https._tcp.pages.default
    expose_external: true
    healthcheck: true
  resizer:
    server: svc.cluster.local service=_https._tcp.resizer.default
    expose_external: true
    healthcheck: true
  uploader:
    server: svc.cluster.local service=_https._tcp.uploader.default
    expose_external: true
    healthcheck: true
  user-manager:
    server: svc.cluster.local service=_https._tcp.user-manager.default
    expose_external: true
    healthcheck: true
    healthcheck_uri: /v1/
