name: auth-proxy
resolver:
  #host: 10.255.3.14
  host: zokets-dns
  ttl: 3s
external_domain_name: mra.nginxps.com
#internal_domain_name: internal.ec2
internal_domain_name: marathon.mesos
services:
  album-manager:
    server: 'album-manager:443'
    expose_external: false
    healthcheck: true
    server_block: true
  pages:
    server: 'pages:443'
    expose_external: true
    healthcheck: true
    server_block: true
  resizer:
    server: 'resizer:443'
    expose_external: false
    healthcheck: true
    healthcheck_uri: /healthcheck
    server_block: true
  uploader:
    server: 'uploader:443'
    expose_external: false
    healthcheck: true
    server_block: true
  user-manager:
    server: 'user-manager:443'
    expose_external: false
    healthcheck: true
    healthcheck_uri: /v1/
    server_block: true
  content-service:
    server: 'content-service:443'
    expose_external: false
    healthcheck: true
    server_block: true
  content-db:
      server: 'content-service:28015'
      expose_external: false
      healthcheck: true
      server_block: true
#  router-mesh:
#    server: 'router-mesh:8889'
#    expose_external: false
#    healthcheck: true
#    healthcheck_uri: /
#    server_block: true
