name: auth-proxy
resolver:
  host: 198.51.100.1 198.51.100.2 198.51.100.3
  ttl: 3s
external_domain_name: mra.nginxps.com
internal_domain_name: marathon.mesos
namespace:
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: pages_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=pages_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
oss_extension: .oss
#ssl_directives:
#  ssl_certificate: /etc/ssl/nginx/fullchain.pem
#  ssl_certificate_key:  /etc/ssl/nginx/privkey.pem
#  ssl_trusted_certificate: /etc/ssl/nginx/chain.pem
services:
  album-manager:
    server: 'marathon.mesos'
    service: 'service=_album-manager._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
    protocol: https
  pages:
    server: 'marathon.mesos'
    service: 'service=_pages._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
    protocol: https
  resizer:
    server: 'marathon.mesos'
    service: 'service=_resizer._tcp'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /healthcheck
    server_block: true
    protocol: https
  uploader:
    server: 'marathon.mesos'
    service: 'service=_uploader._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
    protocol: https
  user-manager:
    server: 'marathon.mesos'
    service: 'service=_user-manager._tcp'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /v1/
    server_block: true
    protocol: https
  router-mesh:
    server: 'marathon.mesos'
    service: 'service=_router-mesh._tcp'
    expose_external: true
    healthcheck: false
    healthcheck_uri: /
    server_block: true
    protocol: https
  content-service:
    server: 'marathon.mesos'
    service: 'service=_content-service._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
    protocol: https
  fake-s3:
    server: 'marathon.mesos'
    service: 'service=_fake-s3._tcp'
    expose_external: true
    healthcheck: false
    server_block: true
    protocol: http
