name: auth-proxy
resolver:
  #host: 10.255.3.14
  host: 198.51.100.1 198.51.100.2 198.51.100.3
  ttl: 3s
external_domain_name: mra.nginxps.com
#internal_domain_name: internal.ec2
internal_domain_name: marathon.mesos
services:
  album-manager:
    server: 'marathon.mesos'
    service: 'service=_album-manager._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
  pages:
    server: 'marathon.mesos'
    service: 'service=_pages._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
  resizer:
    server: 'marathon.mesos'
    service: 'service=_resizer._tcp'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /healthcheck
    server_block: true
  uploader:
    server: 'marathon.mesos'
    service: 'service=_uploader._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
  user-manager:
    server: 'marathon.mesos'
    service: 'service=_user-manager._tcp'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /v1/
    server_block: true
  router-mesh:
    server: 'marathon.mesos'
    service: 'service=_router-mesh._tcp'
    expose_external: true
    healthcheck: true
    healthcheck_uri: /
    server_block: true
  content-service:
    server: 'marathon.mesos'
    service: 'service=_content-service._tcp'
    expose_external: true
    healthcheck: true
    server_block: true
