name: auth-proxy
resolver:
  host: 127.0.0.11
  ttl: 3s
internal_domain_name:
services:
  album-manager:
    server: 'album-manager:443'
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
  pages:
    server: 'pages:443'
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
  resizer:
    server: 'resizer:443'
    expose_external: true
    healthecheck: false
    healthcheck_uri: /healthcheck
    server_block: true
    protocol: https
  uploader:
    server: 'uploader:443'
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
  user-manager:
    server: 'user-manager:443'
    expose_external: true
    healthecheck: false
    healthcheck_uri: /v1/
    server_block: true
    protocol: https
#  router-mesh:
#    server: 'router-mesh'
#    expose_external: true
#    healthcheck: false
#    healthcheck_uri: /
#    server_block: true
#    protocol: https
  content-service:
    server: 'content-service:443'
    expose_external: true
    healthecheck: false
    server_block: true
    protocol: https
  fake-s3:
    server: 'fake-s3:443'
    expose_external: true
    healthcheck: false
    server_block: true
    protocol: http
