name: auth-proxy
resolver:
  host: kube-dns.kube-system.svc.cluster.local
  ttl: 3s
external_domain_name: k8s.mra.nginxps.com
internal_domain_name: svc.cluster.local
namespace: default
log_to_syslog : false
syslog_error_log_location: "syslog:server=localhost:5544 debug"
error_log_location: "/var/log/nginx/error_log debug"
service_log_name: auth_proxy_mra
syslog_access_log_location: "syslog:server=localhost:5544,facility=local6,tag=auth_proxy_mra,severity=info json"
access_log_location: "/var/log/nginx/access_log combined"
oss_extension: .oss
#ssl_directives:
#  ssl_certificate: /etc/ssl/nginx/fullchain.pem
#  ssl_certificate_key:  /etc/ssl/nginx/privkey.pem
#  ssl_trusted_certificate: /etc/ssl/nginx/chain.pem
router_mesh:
  host: router-mesh
  port: 80
services:
  router_mesh:
    server: router-mesh
    scheme: http
    expose_external: true
    healthcheck: true
    healthcheck_uri: /
  pages:
    server: pages
    scheme: http
    expose_external: true
    healthcheck: true
    healthcheck_uri: /
